backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

data:
  butorok:
    file: content/butorok.json
    label: Bútorok
    create: true
    fields:
      - name: id
        label: ID
        type: number
      - name: name
        label: Név
        type: text
      - name: image
        label: Kép
        type: image

  ruhak:
    file: content/ruhak.json
    label: Ruhák
    create: true
    fields:
      - name: id
        label: ID
        type: number
      - name: name
        label: Név
        type: text
      - name: image
        label: Kép
        type: image

  disztargyak:
    file: content/disztargyak.json
    label: Dísztárgyak
    create: true
    fields:
      - name: id
        label: ID
        type: number
      - name: name
        label: Név
        type: text
      - name: image
        label: Kép
        type: image

  egyeb:
    file: content/egyeb.json
    label: Egyéb
    create: true
    fields:
      - name: id
        label: ID
        type: number
      - name: name
        label: Név
        type: text
      - name: image
        label: Kép
        type: image

  home:
    file: content/home.json
    label: Főoldal
    fields:
      - name: text
        label: Bevezető szöveg
        type: text
      - name: slides
        label: Slideshow képei
        type: image-list

  kapcsolat:
    file: content/kapcsolat.json
    label: Kapcsolat
    fields:
      - name: text
        label: Szöveg
        type: text
