backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "butorok"
    label: "Bútorok"
    label_singular: "Bútor"
    folder: "content/butorok"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "ID"
        name: "id"
        widget: "number"
        required: true
      - label: "Név"
        name: "name"
        widget: "string"
        required: true
      - label: "Kép"
        name: "image"
        widget: "image"
        required: true

  - name: "ruhak"
    label: "Ruhák"
    label_singular: "Ruha"
    folder: "content/ruhak"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "ID"
        name: "id"
        widget: "number"
        required: true
      - label: "Név"
        name: "name"
        widget: "string"
        required: true
      - label: "Kép"
        name: "image"
        widget: "image"
        required: true

  - name: "disztargyak"
    label: "Dísztárgyak"
    label_singular: "Dísztárgy"
    folder: "content/disztargyak"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "ID"
        name: "id"
        widget: "number"
        required: true
      - label: "Név"
        name: "name"
        widget: "string"
        required: true
      - label: "Kép"
        name: "image"
        widget: "image"
        required: true

  - name: "egyeb"
    label: "Egyéb"
    label_singular: "Egyéb"
    folder: "content/egyeb"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "ID"
        name: "id"
        widget: "number"
        required: true
      - label: "Név"
        name: "name"
        widget: "string"
        required: true
      - label: "Kép"
        name: "image"
        widget: "image"
        required: true

  - name: "home"
    label: "Főoldal"
    files:
      - label: "Főoldal szöveg és slideshow"
        name: "home"
        file: "content/home.json"
        fields:
          - label: "Bevezető szöveg"
            name: "text"
            widget: "text"
          - label: "Slideshow képei"
            name: "slides"
            widget: "list"
            field:
              label: "Kép"
              name: "slide"
              widget: "image"

  - name: "kapcsolat"
    label: "Kapcsolat"
    files:
      - label: "Kapcsolat szöveg"
        name: "kapcsolat"
        file: "content/kapcsolat.json"
        fields:
          - label: "Szöveg"
            name: "text"
            widget: "text"
